require 'react/rails/asset_variant'
require 'react/rails/railtie'
require 'react/rails/controller_lifecycle'
require 'react/rails/version'
require 'react/rails/component_mount'
require 'react/rails/view_helper'
require 'react/rails/controller_renderer'
